apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout Repo Main
        uses: cloudbees-io/checkout@v1
        with:
          ref: main
      - name: Checkout Repo Feature
        uses: cloudbees-io/checkout@v1
        with:
          ref: feature/test-branch
