apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Deploy Chart A
        uses: docker://alpine:3.18
        shell: sh
        run: |
          echo "Simulating install of nginx 1.2.3 in default"
      - name: Deploy Chart B
        uses: docker://alpine:3.18
        shell: sh
        run: |
          echo "Simulating install of redis 6.0.0 in cache"
